version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "18:00"
    groups:
      non-security:
        patterns:
          - "*"
