name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container: hexpm/elixir:1.19.5-erlang-28.4.1-debian-trixie-20260316
    env:
      MIX_ENV: prod
    steps:
      - name: Install Git
        run: apt update && apt install --yes build-essential git

      - name: Checkout
        uses: actions/checkout@v6

      - name: Fetch Hex Cache
        uses: actions/cache@v5
        id: hex-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Build API
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          mix assets.deploy
          mix release --path export/

      - name: Archive API
        uses: actions/upload-artifact@v7
        with:
          name: api
          path: export/*.tar.gz

  deploy:
    name: "Deploy"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600

      - name: Download API
        uses: actions/download-artifact@v7
        with:
          name: api
          path: export/

      - name: Build and Push Image
        run: |
          docker image build -t registry.digitalocean.com/aj-foster/ftcregion:latest .
          docker image push registry.digitalocean.com/aj-foster/ftcregion:latest

      - name: Get Commit Message
        run: |
          echo "COMMIT_MESSAGE=$(git log --oneline --format=%B -n 1 HEAD | head -n 1)" >> $GITHUB_ENV

      - name: Notify Slack
        id: slack
        uses: slackapi/slack-github-action@v3
        env:
          COMMIT_URL: ${{ format('https://github.com/aj-foster/region-manager/commits/{0}', github.sha) }}
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload-templated: true
          payload: |
            text: "Region Manager deployed: ${{ env.COMMIT_MESSAGE }} (${{ env.COMMIT_URL }})"
            blocks:
              - type: "section",
                text:
                  type: "mrkdwn"
                  text: "*Region Manager* deployed: <${{ env.COMMIT_URL }}|${{ env.COMMIT_MESSAGE }}>"
