on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container: hexpm/elixir:1.17.2-erlang-27.0.1-debian-bookworm-20240812
    env:
      MIX_ENV: prod
    steps:
      - name: Install Git
        run: apt update && apt install --yes build-essential git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Hex Cache
        uses: actions/cache@v4
        id: hex-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Build API
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          mix assets.deploy
          mix release --path export/

      - name: Archive API
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: export/*.tar.gz

  deploy:
    name: "Deploy"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600

      - name: Download API
        uses: actions/download-artifact@v4
        with:
          name: api
          path: export/

      - name: Build and Push Image
        run: |
          docker image build -t registry.digitalocean.com/aj-foster/ftcregion:latest .
          docker image push registry.digitalocean.com/aj-foster/ftcregion:latest

      - name: Get Commit Message
        run: |
          echo "COMMIT_MESSAGE=$(git log --oneline --format=%B -n 1 HEAD | head -n 1)" >> $GITHUB_ENV

      - name: Notify Slack
        id: slack
        uses: slackapi/slack-github-action@v1.26
        with:
          payload: |
            {
              "text": "Region Manager deployed: ${{ env.COMMIT_MESSAGE }} (https://github.com/aj-foster/region-manager/commits/${{ github.sha }})",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Region Manager* deployed: <https://github.com/aj-foster/region-manager/commits/${{ github.sha }}|${{ env.COMMIT_MESSAGE }}>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
